version: "3"

services:
  cookbook_db:
    image: postgres:12.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - cookbook_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cookbook:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: mimic1/cookbook:local
    container_name: cookbook
    command: python src/manage.py runserver 0.0.0.0:8090
    environment:
      KAFKA_BROKERS_URL: kafka_broker:9092
      KAFKA_USE_SSL: "False"
    env_file:
      - .env.dev
    volumes:
      - .:/app/
    ports:
      - "8090:8090"
    depends_on:
      - cookbook_db
      - kafka_broker

  faust:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: mimic1/cookbook:local
    restart: on-failure
    working_dir: /app/src
    command: faust -A consumer worker -l info
    volumes:
      - .:/app/
    environment:
      KAFKA_BROKERS_URL: kafka_broker:9092
      KAFKA_USE_SSL: "False"
    env_file:
      - .env.dev
    depends_on:
      - kafka_broker

  kafka_broker:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  cookbook_db_data:
