apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cookbook
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: cookbook
  targetCPUUtilizationPercentage: 70
